server:
  port: 8081
dubbo:
    scan:
        base-packages: com.xiaoleng.member.dubboService
    application:
        name: member
    protocol:
        name: dubbo
        port: 20880
    registry:
        address: zookeeper://101.132.143.173:2181
        check: false