# server
server:
  port: 8080
  servlet:
    context-path: /boot

# database
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: p2puser
      password: p2poracle
      url: jdbc:mysql://101.132.143.173:3306/spring?characterEncode=utf-8&useSSL=false
      dbcp2:
        max-idle: 10
        min-idle: 5
        max-wait-millis: 1000
        initial-size: 5

# jpa
  jpa:
    hibernate:
      ddl-auto: update  # 建表策略
      dialect: mysql
    show-sql: true  #显示SQL语句

# mybatis
mybatis:
  mapper-locations: classpath:/mappers/*-mapper.xml
  type-aliases-package: com.xiaoleng.admin.domain.po


dubbo:
    application:
        name: admin
    protocol:
        name: dubbo
        port: 20880
    registry:
        address: zookeeper://101.132.143.173:2181